### ISSUE TITLE
Plotting U of Wyoming sounding data

### ISSUE THREAD

**Issue by winash12** [leifdenby/tephigram_python#5]
I have data from University of Wyoming soundings - [http://weather.uwyo.edu/upperair/sounding.html]. Can I use your package to plot this data and create a tephigrram ?

**Comment by leifdenby** [comment]
Yes, that was exactly the data I used when developing this code :) Although when you say "Plotting U" do you mean plotting velocity? I haven't added any wind profile plots yet unfortunately

**Comment by winash12** [comment]
I am getting this error 

Traceback (most recent call last):
  File "test_plot.py", line 70, in <module>
    test_plot_test_parcel()
  File "test_plot.py", line 62, in test_plot_test_parcel
    parcel_info = tephigram.plot_test_parcel(z=z, P=P, T=T, RH=RH)
  File "/usr/local/lib/python3.6/dist-packages/tephigram-0.2.0-py3.6.egg/tephigram/plotter.py", line 396, in plot_test_parcel
    F_parcel, parcel_info = parcel_integrator.find_EL(dqv0=dqv0, dT0=dT0, raise_exception=False, include_info=True, z0=z[0])
  File "/usr/local/lib/python3.6/dist-packages/tephigram-0.2.0-py3.6.egg/tephigram/profile_integration.py", line 457, in find_EL
    dp=dp)
  File "/usr/local/lib/python3.6/dist-packages/tephigram-0.2.0-py3.6.egg/tephigram/profile_integration.py", line 223, in _integrate
    while not stopping_criterion(F_current=F[-1]):
  File "/usr/local/lib/python3.6/dist-packages/tephigram-0.2.0-py3.6.egg/tephigram/profile_integration.py", line 420, in __call__
    p=F_current[Var.p], T=self.thermodynamic_parcel_integration.profile.temp(z=z),
  File "/usr/local/lib/python3.6/dist-packages/tephigram-0.2.0-py3.6.egg/tephigram/profile_integration.py", line 105, in <lambda>
    return lambda z: scipy.interpolate.interp1d(x=self.z, y=y_discrete)(z)
  File "/usr/local/lib/python3.6/dist-packages/scipy-1.1.0-py3.6-linux-x86_64.egg/scipy/interpolate/polyint.py", line 79, in __call__
    y = self._evaluate(x)
  File "/usr/local/lib/python3.6/dist-packages/scipy-1.1.0-py3.6-linux-x86_64.egg/scipy/interpolate/interpolate.py", line 664, in _evaluate
    below_bounds, above_bounds = self._check_bounds(x_new)
  File "/usr/local/lib/python3.6/dist-packages/scipy-1.1.0-py3.6-linux-x86_64.egg/scipy/interpolate/interpolate.py", line 696, in _check_bounds
    raise ValueError("A value in x_new is above the interpolation "
ValueError: A value in x_new is above the interpolation range.

for this data file 

#10410 EDZE Essen Observations at 00Z 20 Mar 2019
#-----------------------------------------------------------------------------
#   PRES   HGHT   TEMP   DWPT   RELH   MIXR   DRCT   SKNT   THTA   THTE   THTV
#    hPa     m      C      C      %    g/kg    deg   knot     K      K      K 
#-----------------------------------------------------------------------------
 1014.0    147    5.2    0.6     72   3.96    170      2  277.2  288.3  277.9
 1013.0    155    5.0    0.6     73   3.96    172      2  277.1  288.2  277.8
 1003.0    233    7.6   -0.4     57   3.72    194      8  280.5  291.1  281.1
 1000.0    257    7.4    0.4     61   3.96    200     10  280.6  291.8  281.2
  959.0    600    4.5   -0.2     71   3.94    245     10  281.0  292.2  281.7
  925.0    895    2.0   -0.8     82   3.92    250      8  281.4  292.5  282.0
  890.0   1204   -0.7   -1.8     92   3.78    255      9  281.7  292.5  282.3
  858.0   1496   -2.5   -6.3     75   2.79    260     10  282.8  290.9  283.3
  850.0   1570   -2.9   -7.5     71   2.57    270     12  283.1  290.6  283.5
  833.0   1730   -3.9   -9.9     63   2.17    278     11  283.7  290.1  284.1
  817.0   1882   -5.2  -10.2     68   2.16    285     10  283.9  290.3  284.2
  797.0   2077   -6.9  -10.6     75   2.15    308     10  284.1  290.5  284.4
  781.0   2235   -6.1  -24.1     23   0.70    327     11  286.6  288.9  286.7
  745.0   2604   -5.7  -27.5     16   0.54     10     12  290.9  292.7  291.0
  743.0   2626   -5.7  -27.7     16   0.53      9     12  291.1  292.9  291.2
  710.0   2980   -7.1  -24.5     24   0.75    350     14  293.4  295.9  293.6
  700.0   3091   -7.5  -23.5     27   0.83    355     16  294.1  296.9  294.3
  677.0   3347   -8.6  -26.1     23   0.67     10     19  295.8  298.0  295.9
  565.0   4736  -14.5  -40.5      9   0.20      2     22  304.5  305.2  304.5
  553.0   4898  -15.7  -32.7     22   0.44      1     23  304.9  306.5  305.0
  550.0   4939  -16.1  -24.1     50   1.00      1     23  304.9  308.3  305.1
  546.0   4994  -16.1  -44.1      7   0.14      1     23  305.6  306.1  305.6
  539.0   5091  -16.9  -21.8     66   1.25      0     23  305.7  309.9  306.0
  536.0   5132  -17.3  -21.6     69   1.28      0     23  305.8  310.0  306.0
  532.0   5189  -17.7  -24.7     54   0.98      1     24  305.9  309.2  306.1
  530.0   5217  -18.1  -20.8     79   1.38      1     25  305.8  310.4  306.0
  500.0   5650  -20.5  -24.4     71   1.07      5     31  308.0  311.6  308.2
  471.0   6086  -23.5  -27.9     67   0.82     15     37  309.6  312.5  309.8
  443.0   6533  -26.5  -31.5     63   0.62     13     40  311.2  313.5  311.4
  400.0   7260  -32.3  -36.9     64   0.41     10     45  312.9  314.4  313.0
  392.0   7402  -33.5  -36.9     71   0.41     10     47  313.2  314.7  313.2
  367.0   7861  -37.9  -42.5     62   0.25     12     55  313.3  314.2  313.3
  363.0   7937  -38.1  -48.1     34   0.14     12     56  314.0  314.5  314.0
  350.0   8187  -39.9  -51.9     27   0.09     13     60  314.8  315.2  314.9
  312.0   8957  -46.8  -55.8     35   0.06     15     74  315.8  316.0  315.8
  300.0   9220  -49.1  -57.1     39   0.06     10     74  316.0  316.3  316.1
  292.0   9397  -50.7  -57.7     43   0.05     11     74  316.2  316.4  316.2
  286.0   9533  -50.3  -67.3     12   0.02     11     74  318.7  318.7  318.7
  260.0  10150  -55.7  -62.7     41   0.03     14     74  319.5  319.7  319.5
  255.0  10274  -56.7  -64.7     36   0.03     15     74  319.8  319.9  319.9
  250.0  10400  -57.7  -66.7     31   0.02     10     70  320.2  320.2  320.2
  247.0  10476  -57.9  -68.9     23   0.01     10     69  321.0  321.0  321.0
  237.0  10735  -56.9  -69.9     18   0.01     12     66  326.3  326.4  326.3
  220.0  11198  -60.2  -70.5     25   0.01     15     60  328.1  328.2  328.1
  213.0  11400  -61.7  -70.7     29   0.01      5     56  328.9  329.0  328.9
  206.0  11606  -60.9  -73.3     18   0.01    355     62  333.4  333.4  333.4
  203.0  11696  -60.5  -74.5     14   0.01    360     55  335.4  335.4  335.4
  201.0  11758  -55.3  -77.3      5   0.01      3     51  344.5  344.6  344.5
  200.0  11790  -54.7  -79.7      3   0.00      5     49  346.0  346.0  346.0
  198.0  11855  -54.3  -80.8      2   0.00     10     45  347.6  347.6  347.6
  196.0  11920  -53.9  -81.9      2   0.00      8     43  349.3  349.3  349.3
  188.0  12191  -53.3  -82.3      2   0.00      0     37  354.4  354.4  354.4
  167.0  12961  -51.7  -83.4      1   0.00    355     45  369.3  369.3  369.3
  159.0  13280  -51.0  -83.8      1   0.00    350     41  375.7  375.7  375.7
  158.0  13321  -50.9  -83.9      1   0.00    352     40  376.5  376.5  376.5
  150.0  13660  -51.9  -83.9      1   0.00      5     33  380.4  380.4  380.4
  143.0  13963  -52.9  -84.4      1   0.00    340     27  383.9  384.0  383.9
  133.0  14422  -54.4  -85.2      1   0.00    345     43  389.3  389.3  389.3
  118.0  15181  -56.9  -86.5      1   0.00    355     27  398.3  398.3  398.3
  100.0  16230  -60.3  -88.3      1   0.00     15     35  410.9  411.0  410.9

#Station information and sounding indices
#                         Station identifier: EDZE
#                             Station number: 10410
#                           Observation time: 190320/0000
#                           Station latitude: 51.40
#                          Station longitude: 6.97
#                          Station elevation: 147.0
#                            Showalter index: 15.24
#                               Lifted index: 14.61
#    LIFT computed using virtual temperature: 14.72
#                                SWEAT index: 54.39
#                                    K index: -5.90
#                         Cross totals index: 13.00
#                      Vertical totals index: 17.60
#                        Totals totals index: 30.60
#      Convective Available Potential Energy: 0.00
#             CAPE using virtual temperature: 0.00
#                      Convective Inhibition: 0.00
#             CINS using virtual temperature: 0.00
#                     Bulk Richardson Number: 0.00
#          Bulk Richardson Number using CAPV: 0.00
#  Temp [K] of the Lifted Condensation Level: 271.96
#Pres [hPa] of the Lifted Condensation Level: 898.74
#     Mean mixed layer potential temperature: 280.40
#              Mean mixed layer mixing ratio: 3.92
#              1000 hPa to 500 hPa thickness: 5393.00
#Precipitable water [mm] for entire sounding: 10.40

**Comment by winash12** [comment]
Any update on this?
